// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Target struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string   `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Target) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Target) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type Task struct {
	TraceId              string    `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedTs            int64     `protobuf:"varint,2,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`
	BrokerId             string    `protobuf:"bytes,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Payer                string    `protobuf:"bytes,4,opt,name=payer,proto3" json:"payer,omitempty"`
	PayedTs              int64     `protobuf:"varint,5,opt,name=payed_ts,json=payedTs,proto3" json:"payed_ts,omitempty"`
	AssetId              string    `protobuf:"bytes,6,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount               string    `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Memo                 string    `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	Targets              []*Target `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Task) GetCreatedTs() int64 {
	if m != nil {
		return m.CreatedTs
	}
	return 0
}

func (m *Task) GetBrokerId() string {
	if m != nil {
		return m.BrokerId
	}
	return ""
}

func (m *Task) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *Task) GetPayedTs() int64 {
	if m != nil {
		return m.PayedTs
	}
	return 0
}

func (m *Task) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *Task) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Task) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Task) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type CreateTaskReq struct {
	TraceId              string    `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AssetId              string    `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Memo                 string    `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	Targets              []*Target `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateTaskReq) Reset()         { *m = CreateTaskReq{} }
func (m *CreateTaskReq) String() string { return proto.CompactTextString(m) }
func (*CreateTaskReq) ProtoMessage()    {}
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *CreateTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskReq.Unmarshal(m, b)
}
func (m *CreateTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskReq.Marshal(b, m, deterministic)
}
func (m *CreateTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskReq.Merge(m, src)
}
func (m *CreateTaskReq) XXX_Size() int {
	return xxx_messageInfo_CreateTaskReq.Size(m)
}
func (m *CreateTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskReq proto.InternalMessageInfo

func (m *CreateTaskReq) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *CreateTaskReq) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *CreateTaskReq) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *CreateTaskReq) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type FindTaskReq struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTaskReq) Reset()         { *m = FindTaskReq{} }
func (m *FindTaskReq) String() string { return proto.CompactTextString(m) }
func (*FindTaskReq) ProtoMessage()    {}
func (*FindTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *FindTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTaskReq.Unmarshal(m, b)
}
func (m *FindTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTaskReq.Marshal(b, m, deterministic)
}
func (m *FindTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTaskReq.Merge(m, src)
}
func (m *FindTaskReq) XXX_Size() int {
	return xxx_messageInfo_FindTaskReq.Size(m)
}
func (m *FindTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindTaskReq proto.InternalMessageInfo

func (m *FindTaskReq) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Target)(nil), "fox.one.airdrop.Target")
	proto.RegisterType((*Task)(nil), "fox.one.airdrop.Task")
	proto.RegisterType((*CreateTaskReq)(nil), "fox.one.airdrop.CreateTaskReq")
	proto.RegisterType((*FindTaskReq)(nil), "fox.one.airdrop.FindTaskReq")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x9a, 0x6e, 0x9a, 0x29, 0x22, 0x0c, 0x6a, 0xe3, 0x5f, 0x4a, 0x4f, 0x3d, 0x05,
	0xac, 0x47, 0x0f, 0x82, 0x82, 0xd0, 0x83, 0x97, 0x98, 0x93, 0x97, 0xb2, 0xed, 0xae, 0x12, 0x42,
	0xbb, 0x71, 0x77, 0x2b, 0xfa, 0x0d, 0x04, 0xfd, 0xd0, 0xb2, 0xb3, 0x4a, 0x5b, 0x5b, 0xff, 0xdc,
	0xf6, 0xcd, 0x6e, 0xde, 0xfc, 0xde, 0x23, 0x00, 0x96, 0x9b, 0x2a, 0xab, 0xb5, 0xb2, 0x0a, 0xb7,
	0xef, 0xd5, 0x73, 0xa6, 0x66, 0x32, 0xe3, 0xa5, 0x16, 0x5a, 0xd5, 0xbd, 0x1b, 0x60, 0x05, 0xd7,
	0x0f, 0xd2, 0x62, 0x07, 0xe2, 0xb9, 0x91, 0x7a, 0x54, 0x8a, 0x34, 0xe8, 0x06, 0xfd, 0x24, 0x67,
	0x4e, 0x0e, 0x05, 0xee, 0x01, 0xe3, 0x53, 0x35, 0x9f, 0xd9, 0x34, 0xf4, 0x73, 0xaf, 0x10, 0x21,
	0x9a, 0xca, 0xa9, 0x4a, 0x1b, 0x34, 0xa5, 0x73, 0xef, 0x35, 0x84, 0xa8, 0xe0, 0xa6, 0xc2, 0x7d,
	0x68, 0x59, 0xcd, 0x27, 0x72, 0x61, 0x17, 0x93, 0x1e, 0x0a, 0x3c, 0x06, 0x98, 0x68, 0xc9, 0xad,
	0x14, 0x23, 0x6b, 0xc8, 0xb3, 0x91, 0x27, 0x9f, 0x93, 0xc2, 0xe0, 0x21, 0x24, 0x63, 0xad, 0x2a,
	0x4f, 0xe2, 0xbd, 0x5b, 0x7e, 0x30, 0x14, 0xb8, 0x03, 0xcd, 0x9a, 0xbf, 0x48, 0x9d, 0x46, 0x74,
	0xe1, 0x85, 0x5b, 0xe6, 0x0e, 0xe4, 0xd7, 0x24, 0xbf, 0x98, 0x74, 0x61, 0xdc, 0x15, 0x37, 0x46,
	0x5a, 0x67, 0xc6, 0x3c, 0x07, 0xe9, 0x95, 0x5c, 0xf1, 0xc6, 0x5c, 0xad, 0x45, 0x2e, 0x3c, 0x85,
	0xd8, 0x52, 0x4d, 0x26, 0x4d, 0xba, 0x8d, 0x7e, 0x7b, 0xd0, 0xc9, 0xbe, 0x35, 0x99, 0xf9, 0x1a,
	0xf3, 0xaf, 0x77, 0xbd, 0xf7, 0x00, 0xb6, 0xae, 0x28, 0x95, 0x2b, 0x24, 0x97, 0x8f, 0xbf, 0x75,
	0xb2, 0x8c, 0x19, 0xae, 0x62, 0x6e, 0xa8, 0x79, 0x19, 0x27, 0xfa, 0x27, 0x4e, 0x1f, 0xda, 0xd7,
	0xe5, 0x4c, 0xfc, 0xcd, 0x32, 0x78, 0x0b, 0xa0, 0xed, 0x9e, 0xdd, 0x4a, 0xfd, 0x54, 0x4e, 0x24,
	0x5e, 0x00, 0xf3, 0x39, 0xf0, 0x64, 0x6d, 0xcb, 0x4a, 0xc0, 0x83, 0xdd, 0x0d, 0x14, 0xa6, 0xc2,
	0x73, 0x88, 0xdc, 0x6a, 0x3c, 0x5a, 0xbb, 0x5e, 0x22, 0xfa, 0xe1, 0xe3, 0xcb, 0xe8, 0x2e, 0xac,
	0xc7, 0x63, 0x46, 0xbf, 0xef, 0xd9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0xc6, 0xe5, 0xb3,
	0xcc, 0x02, 0x00, 0x00,
}
